<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>32fcc318-e522-40ec-9831-af316d19db94</elementGuidId>
    <imagePath></imagePath>
    <name>input_r4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[3]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r4\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r4:') and equals(@name,'shipping_address.address_line_1') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>a6cf249b-e7e5-441e-89f6-8cc7d00de320</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r4:</value>
        <webElementGuid>6ef74e3a-4a4f-46a8-b68a-903d69cfc238</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.address_line_1</value>
        <webElementGuid>8225ae51-caad-4833-9d51-d028db6f36de</webElementGuid>
    </webElementProperties>
</WebElementEntity>