<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1fed03b9-3e4d-41eb-9757-6061ce2e72d4</elementGuidId>
    <imagePath></imagePath>
    <name>input_rc</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[3]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:rc\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':rc:') and equals(@name,'billing_address.address_line_1') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>f5a09d33-252d-4bda-aed7-2772fc14b754</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:rc:</value>
        <webElementGuid>fb44556b-8e65-4793-bcd5-ed2f2ebbeb6e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.address_line_1</value>
        <webElementGuid>33a5cf1e-f632-4ac8-b872-859867f8dbdd</webElementGuid>
    </webElementProperties>
</WebElementEntity>