<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>45c3b20c-c7e9-4745-961e-0ab46cf61a30</elementGuidId>
    <imagePath></imagePath>
    <name>input_rf</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[6]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:rf\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':rf:') and equals(@name,'billing_address.state') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>7371e5cb-d79f-4e0b-bdd6-cd0b60a630ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:rf:</value>
        <webElementGuid>2e27ebad-6b92-4341-b741-657d9f97d2e1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.state</value>
        <webElementGuid>5dcd1890-5175-4b09-bf87-04a63b4717a6</webElementGuid>
    </webElementProperties>
</WebElementEntity>