<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c6be3ad4-307d-44f2-9016-f22f30c63872</elementGuidId>
    <imagePath></imagePath>
    <name>input_r6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[5]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r6\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r6:') and equals(@name,'shipping_address.city') and equals(@class,'MuiInputBase-input MuiInput-input css-mnn31')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiInput-input css-mnn31</value>
        <webElementGuid>1857c119-dae6-4b4e-9309-23e6e6a580fc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r6:</value>
        <webElementGuid>4cb7411c-5e88-4fde-b4c9-dc4f2bcfe138</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.city</value>
        <webElementGuid>e204e3d3-13d3-4524-a06f-fd5ee1221a56</webElementGuid>
    </webElementProperties>
</WebElementEntity>