<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2096387b-55a9-4dd4-80bd-d5f5971f88d2</elementGuidId>
    <imagePath></imagePath>
    <name>select_r8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[2]/div[1]/div[7]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:r8\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':r8:') and equals(@name,'shipping_address.country_id') and equals(@class,'MuiNativeSelect-select MuiNativeSelect-standard MuiInputBase-input MuiInput-input css-1vynybe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiNativeSelect-select MuiNativeSelect-standard MuiInputBase-input MuiInput-input css-1vynybe</value>
        <webElementGuid>923c76f2-7004-442b-a0fb-6d82c6bf30d9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:r8:</value>
        <webElementGuid>b75563ce-2661-464d-ae8c-6e1e3b801f29</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>shipping_address.country_id</value>
        <webElementGuid>f2ae9d89-c02d-47de-bfb3-a44954a86d00</webElementGuid>
    </webElementProperties>
</WebElementEntity>