<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>43027db5-f2e2-4449-af83-688c63080e21</elementGuidId>
    <imagePath></imagePath>
    <name>select_rg</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[1]/div[7]/div[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\:rg\:</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,':rg:') and equals(@name,'billing_address.country_id') and equals(@class,'MuiNativeSelect-select MuiNativeSelect-standard MuiInputBase-input MuiInput-input css-1vynybe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiNativeSelect-select MuiNativeSelect-standard MuiInputBase-input MuiInput-input css-1vynybe</value>
        <webElementGuid>376613e4-4dcf-4f65-a145-e3608e1d6845</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>:rg:</value>
        <webElementGuid>48d0ee13-a17e-4ef2-9229-09f2acc07a31</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>billing_address.country_id</value>
        <webElementGuid>e1c27afd-879b-4334-84fe-d153383781b4</webElementGuid>
    </webElementProperties>
</WebElementEntity>