<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>380edbe1-77dd-4d63-ae73-d281e402b74b</elementGuidId>
    <imagePath></imagePath>
    <name>link_svg patterns</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[1]/a[24]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#leftmenuinnerinner &gt; a:nth-child(27)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'SVG Patterns')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name=" SVG Patterns"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>SVG Patterns</value>
        <webElementGuid>0000cc76-e46b-4efc-b30d-45517cfab582</webElementGuid>
    </webElementProperties>
</WebElementEntity>