<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c9255e09-6895-49bc-964f-40a582cc861a</elementGuidId>
    <imagePath></imagePath>
    <name>link_svg defines vector-based graphics in xml</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/div[1]/p[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>p:nth-child(6) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'SVG defines vector-based graphics in XML')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="SVG defines vector-based"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>SVG defines vector-based graphics in XML</value>
        <webElementGuid>0000cc76-e46b-4efc-b30d-45517cfab582</webElementGuid>
    </webElementProperties>
</WebElementEntity>