<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fb5f693e-6f03-4cf1-b58c-215e986bb317</elementGuidId>
    <imagePath></imagePath>
    <name>link_html canvas</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[1]/a[46]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>a:nth-child(56)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'HTML Canvas')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name=" HTML Canvas"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>HTML Canvas</value>
        <webElementGuid>d904a0a9-1531-41ae-b8b8-3ae62588d91a</webElementGuid>
    </webElementProperties>
</WebElementEntity>