<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a33faee4-4a1b-4082-87d8-3a24f52ac555</elementGuidId>
    <imagePath></imagePath>
    <name>label_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for='\31 52171-case-638']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-outline-secondary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-outline-secondary</value>
        <webElementGuid>63d8cbd2-72f7-4ac1-abe0-3e96603deda5</webElementGuid>
    </webElementProperties>
</WebElementEntity>