<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3e60a353-e107-47eb-b04a-b9966a6cd027</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_category_accessories</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.horizontal-menu__element[href='\/category\/accessories']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'horizontal-menu__element is-link is-root')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>horizontal-menu__element is-link is-root</value>
        <webElementGuid>3765c717-57b9-4ce2-ba70-71ae5a27ea3b</webElementGuid>
    </webElementProperties>
</WebElementEntity>