<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b1486366-175a-4c2b-b1c8-e8fb03966243</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_category_phone</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.horizontal-menu__element.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'horizontal-menu__element is-link is-root active children-visible')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>horizontal-menu__element is-link is-root active children-visible</value>
        <webElementGuid>337bdccf-db89-4b76-97fd-775807fef664</webElementGuid>
    </webElementProperties>
</WebElementEntity>